### PR TITLE
membership verifier in ts lib

### PR DESCRIPTION
**Pull request by lsankar4033**
For https://github.com/personaelabs/spartan-ecdsa/issues/8

### CODE REVIEW

**Comment by lsankar4033** [comment]
@DanTehrani am continuing to investigate, but in case you have a spare minute, does anything obvious look wrong in the way I've structured `membership_verifier` here?

verification is failing for me locally (i.e. in `membership_nizk` test)

**Comment by DanTehrani** [comment]
@lsankar4033  will check it out now!

**Comment by DanTehrani** [comment]
@lsankar4033  It was just the prover returning the public input incorrectly (was missing the `root`), my bad.
Pushed the fix f41768f14a7ce7a3e998a0b008ee55a824fe1577!

**Comment by lsankar4033** [comment]
wow that was fast 🐐

**Comment by lsankar4033** [comment]
still failing, but I'll dig deeper

**Comment by DanTehrani** [comment]
@lsankar4033 
Hmm in my env membership_nizk.test.ts passes. 

Maybe run these scripts to compile the circuits to the latest ones?
- [addr_membership_circuit.sh](https://github.com/personaelabs/spartan-ecdsa/blob/main/scripts/addr_membership_circuit.sh)
- [pubkey_membership_circuit.sh](https://github.com/personaelabs/spartan-ecdsa/blob/main/scripts/pubkey_membership_circuit.sh)

**Comment by DanTehrani** [comment]
(forgot to add that instruction to the readme, will add it if the above works)

**Comment by lsankar4033** [comment]
@DanTehrani ready for review/merge!

**Review by DanTehrani — APPROVED** [review]
LGTM

**Pull request merged**
