### PR TITLE
Add Personae GCP buckets

### PR DESCRIPTION
**Pull request by lsankar4033**
1. created dedicated Personae Labs GCP buckets (not tracked in this repo) 
2. changed default URLs for proving artifacts in ts lib to use the new buckets

### CODE REVIEW

**Review by DanTehrani — APPROVED** [review]
Thanks! Confirmed that web/ proving works with the new keys!

**Comment by DanTehrani** [comment]
@lsankar4033 
Sorry, actually my confirmation was totally false (checked at the wrong commit). 

I can't access the files hosted e.g https://storage.googleapis.com/personae-proving_keys/spartan_wasm_bg.wasm
Could u check the bucket config?

**Comment by DanTehrani** [comment]
Also/or can u give me read/write access to the bucket?

**Comment by lsankar4033** [comment]
@DanTehrani Ah my bad, typo in bucket names. fixed here: https://github.com/personaelabs/spartan-ecdsa/pull/13/files

**Pull request merged**
